namespace :meteor do
  desc 'Run Meteor in local environment on specified port'
  task :run do
    sh 'meteor run --port <%= @port %>'

    # Meteor server running on: http://test.dev/
  end

  desc 'Run unit tests with Laika'
  task :test do
    begin
      md_pid = Process.spawn 'mongod --smallfiles --noprealloc --nojournal'
      Process.detach md_pid

      sh 'laika'
    ensure
      Process.kill 'INT', md_pid
    end
  end
end

task :default => :test
